version: 1.0.{build}
image: Visual Studio 2017
before_build:
- nuget restore
- git reset --hard
build:
  verbosity: minimal
after_build:
- nuget pack NuGet -Version %APPVEYOR_BUILD_VERSION%
- appveyor PushArtifact Loom.Fody.%APPVEYOR_BUILD_VERSION%.nupkg
