# This is the only place where a version is configured. The NuGet package
# will get its version from this, without the "-b{build}" suffix.
version: 0.3.2-b{build}
image: Visual Studio 2017
before_build:
- nuget restore
- git reset --hard
- ps: sc package_version.txt ($env:APPVEYOR_BUILD_VERSION -replace "-b\d+", "")
- ps: echo (gc package_version.txt)
- powershell ".\change-nuspec-version.ps1 NuGet\Loom.Fody.nuspec (gc package_version.txt)"
build:
  verbosity: minimal
after_build:
- ps: appveyor PushArtifact "NuGetBuild\Loom.Fody.$(gc package_version.txt).nupkg"
