version: 1.0.{build}
image: Visual Studio 2017
before_build:
- nuget restore
- git reset --hard
- ps: |
$path = "NuGet\Loom.Fody.nuspec"
$version = %APPVEYOR_BUILD_VERSION%

$file = Get-Item $path

$xml = [xml](Get-Content $path)

$xml.package.metadata.version = $version

$xml.Save((Join-Path (pwd) $path))

build:
  verbosity: minimal
after_build:
- appveyor PushArtifact NuGetBuild\Loom.Fody.%APPVEYOR_BUILD_VERSION%.nupkg
