version: 1.0.{build}
image: Visual Studio 2017
before_build:
- nuget restore
- git reset --hard
- ps: '& "change-nuspec-version.ps1 NuGet\Loom.Fody.nuspec %APPVEYOR_BUILD_VERSION%"'
build:
  verbosity: minimal
after_build:
- appveyor PushArtifact NuGetBuild\Loom.Fody.%APPVEYOR_BUILD_VERSION%.nupkg
