version: 1.0.0-alpha-b{build}
image: Visual Studio 2017
before_build:
- nuget restore
- git reset --hard
- ps: sc package_version.txt ($APPVEYOR_BUILD_VERSION -replace "-b\d+", "")
- powershell ".\change-nuspec-version.ps1 NuGet\Loom.Fody.nuspec (gc package_version.txt)"
build:
  verbosity: minimal
after_build:
- ps: appveyor PushArtifact "NuGetBuild\Loom.Fody.$(gc package_version.txt).nupkg"
